image: jekyll/jekyll:4.2.0

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: bundle update # runs during prebuild
    command: bundle exec jekyll serve --draft --future --incremental -P 4000
