on: 
  [push,issues,pull_request]

jobs:
  test_js:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn
      - name: Testing the Js
        uses: TheShubham99/movingblocks.github.com/actions@master